cc_library(
    name = "nsrobot",
    hdrs = ["nsrobot.h"],
    srcs = ["nsrobot.cpp"],
    visibility = ["//visibility:public"]
)

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [":nsrobot"],
    visibility = ["//visibility:public"]
)
